### ISSUE TITLE
Performance Request

### ISSUE THREAD

**Issue by JulianSkies** [zymex22/Project-RimFactory-Revived#442]
Not quite a bug, but some people have noticed spikes in performance, i've done some looking around at the Performance Analyzer and there's some pretty big spikes so I figured i'd share what I pulled up. Seems to be related to the number of items that exist around, of which I have a lot.

**Screenshots**
![PRF Perf 1](https://user-images.githubusercontent.com/20136904/116159648-02c37a00-a6c7-11eb-8d7a-6d545febea89.png)
![PRF Perf 2](https://user-images.githubusercontent.com/20136904/116159656-03f4a700-a6c7-11eb-8684-27250d0e0d68.png)
![PRF Perf 3](https://user-images.githubusercontent.com/20136904/116159660-05be6a80-a6c7-11eb-9747-2c4ef3e10c1b.png)

**Modlist (please complete the following information):**
Here's a hugslog because it's way easier than a modlist and also has a list of patches: https://gist.github.com/HugsLibRecordkeeper2/3263fb705b841edc9549fee5a04981f5

**Additional context**
Particular performance request was first commented on by a third party, I simply offered to run the profiler and report to you all.

**Comment by Sn1p3rr3c0n** [comment]
Note: the peaks of `Patch_Building_Storage_Accepts` should be resolved with #449

**Comment by zymex22** [comment]
@JulianSkies have this been better after latest updates or still a problem?

**Comment by zymex22** [comment]
closed we open if still a problem
